### PR TITLE
update ui 2

### LINKED ISSUE #59: Update View Page FXML

### PR DESCRIPTION
**Pull request by farisanadia**
fixed empty list cell colors:
- fixed show panel colors

### CODE REVIEW

**Review by phyliciachristel — APPROVED** [review]
wow nice colors!!! LGTM

**Comment by farisanadia** [comment]
Updated person cards to match previously agreed upon designs:
image
View state:
image

Areas of concern:
- When person is selected, color does not change for the fields
image
- Certain text spacing inconsistencies: between name and tag etc.
- Long text (like names) truncates, should go to new line instead:
image

**Comment by farisanadia** [comment]
Text no longer truncates if too long, goes to next line instead. Phone number field pushed to next line to accommodate potentially longer names. Also fixed some text sizing inconsistencies
image
Not sure why index prints on different line. Will look into it

**Comment by farisanadia** [comment]
Final result:
image
image

**Review by cfyjoanna — APPROVED** [review]
love the kids colouring book theme. LGTM

**Pull request merged**
