### PR TITLE
Update SampleData

### PR DESCRIPTION
**Pull request by jwdavis0200**
Updated Sample Data for Pupilist when starting without data.

I don't believe this breaches feature freeze but somebody do confirm!

### CODE REVIEW

**Review by AshiqurRah — APPROVED** [review]
LGTM!!

**Review by farisanadia — APPROVED** [review]
LGTM but does this mean we need change the user guide photos also

**Comment by AshiqurRah** [comment]
@farisanadia i would say yes so that users are more familiar with the format they have

**Comment by phyliciachristel** [comment]
update the quick start pic

**Comment by jwdavis0200** [comment]
okkie updated the Ui.png for the user guide

**Comment by phyliciachristel** [comment]
i feel like u shld use a less stretched out pic cos its kinda ugly the smaller one looks better

**Comment by jwdavis0200** [comment]
ah sorryyy ok will push another pr

**Pull request merged**
