### PR TITLE
Updated UI, Person Cards not completed

### LINKED ISSUE #59: Update View Page FXML

### PR DESCRIPTION
**Pull request by farisanadia**
Updated colors for command input, result display, menu bar. 
Current view: 
image
To be completed: 
- personcards ui - colors, arrangment of fields
- change tag colors
- fix logo size

### CODE REVIEW

**Comment by farisanadia** [comment]
darkened scroll bar color to match UI, changed person card color to match border
current look [1st box selected color]:
image

**Comment by farisanadia** [comment]
updated help window to match main window ui.
current look:
image

**Review by cfyjoanna — APPROVED** [review]
beautiful. LGTM

**Comment by farisanadia** [comment]
current help page: 
image
current home page:
image
home page with selected card, response field text:
image

FXML now includes label for grade progress, homework, assignment, attendance and lesson plan
Removed headers from fields with lists
Added header to lesson plan
Moved grade progress field to be below phone number

**Pull request merged**
